# Generated by Django 5.1 on 2024-09-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_site_note_urls_site_video_urls_alter_record_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='azteca',
            field=models.BooleanField(default=False),
        ),
    ]
