# Generated by Django 5.1 on 2024-09-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_insert_data'),
    ]

    operations = [
        migrations.RunSQL('''
INSERT INTO server_site (name, sitemap_url, video_sitemap_url, note_sitemap_url, video_urls, note_urls)
VALUES
('Azteca UNO', NULL, 'https://www.tvazteca.com/aztecauno/sitemap-video.xml', 'https://www.tvazteca.com/aztecauno/sitemap-content.xml', '[]', '[]'),
('Azteca 7', NULL, 'https://www.tvazteca.com/azteca7/sitemap-video.xml', 'https://www.tvazteca.com/azteca7/sitemap-content.xml', '[]', '[]'),
('Deportes', NULL, 'https://www.tvazteca.com/aztecadeportes/sitemap-video.xml', 'https://www.tvazteca.com/aztecadeportes/sitemap-content.xml', '[]', '[]'),
('ADN40', NULL, 'https://www.adn40.mx/sitemap-video.xml', 'https://www.adn40.mx/sitemap-content.xml', '[]', '[]'),
('A+', NULL, 'https://www.tvazteca.com/aztecanoticias/sitemap-video.xml', 'https://www.tvazteca.com/aztecanoticias/sitemap-content.xml', '[]', '[]'),
('Noticias', NULL, 'https://www.tvazteca.com/amastv/sitemap-video.xml', 'https://www.tvazteca.com/amastv/sitemap-content.xml', '[]', '[]'),
('Televisa', NULL, 'https://www.nmas.com.mx/nmas-video/s3fs-public/sitemap-video-last.xml', 'https://tools.nmas.live/rss/sitemap-news.xml', '[]', '[]'),
('El Heraldo', 'https://heraldodemexico.com.mx/sitemaps/txt/t62.txt', NULL, NULL, '[]', '[]'),
('El Universal', 'https://www.eluniversal.com.mx/arc/outboundfeeds/general/?outputType=xml', NULL, NULL, '[]', '[]'),
('Milenio', 'https://www.milenio.com/sitemap/google-news/sitemap-google-news-current-1.xml', NULL, NULL, '[]', '[]'),
('NY Times', NULL, 'https://www.nytimes.com/sitemaps/new/video.xml.gz', 'https://www.nytimes.com/sitemaps/new/news.xml.gz', '[]', '[]'),
('Infobae', NULL, 'https://www.infobae.com/arc/outboundfeeds/news-sitemap2/category/teleshow/', 'https://www.infobae.com/arc/outboundfeeds/news-sitemap2/', '[]', '[]'),
('AS', NULL, 'https://feeds.as.com/mrss-s/list/as/site/as.com/video/', 'https://feeds.as.com/mrss-s/pages/as/site/as.com/section/opinion/portada/', '[]', '[]'),
('Terra', NULL, 'https://www.terra.com.mx/rss/un_foto.html', 'https://www.terra.com.mx/rss/un_foto.html', '[]', '[]');

                          ''')
    ]
