# Generated by Django 5.1 on 2024-09-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
