# Generated by Django 5.1 on 2024-09-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note_value', models.FloatField(blank=True, null=True)),
                ('video_value', models.FloatField(blank=True, null=True)),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('azteca', models.BooleanField(default=False)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sitemap_url', models.URLField(null=True)),
                ('video_sitemap_url', models.URLField(null=True)),
                ('note_sitemap_url', models.URLField(null=True)),
                ('video_urls', models.JSONField(null=True)),
                ('note_urls', models.JSONField(null=True)),
            ],
        ),
    ]
