# Generated by Django 5.1 on 2024-09-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='note_urls',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='video_urls',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='note_sitemap_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='sitemap_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='video_sitemap_url',
            field=models.URLField(null=True),
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
