# Generated by Django 5.1 on 2024-11-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20241025_1416'),
    ]

    operations = [
            migrations.RunSQL('''
                              update server_site set name = "A+" where name = "Noticias";
                              update server_site set name = "Noticias" where name = "A+";
                          ''')
    ]
