# Generated by Django 5.1 on 2024-11-03 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20241102_0117'),
    ]

    operations = [
        migrations.RunSQL('''
                       INSERT INTO server_localsite (name, note_urls, video_urls) VALUES
('Azteca BajaCalifornia', 
    JSON_ARRAY(
        'https://www.tvaztecabajacalifornia.com/espectaculos/mariah-carey-anuncia-el-inicio-la-temporada-navidad-2024-en-halloween',
        'https://www.tvaztecabajacalifornia.com/espectaculos/belinda-invita-a-majo-aguilar-a-su-fiesta-halloween-2024',
        'https://www.tvaztecabajacalifornia.com/noticias/dolar-tijuana-hoy-viernes-1-noviembre-2024-tipo-cambio'
    ),
    JSON_ARRAY(
        'https://www.tvaztecabajacalifornia.com/noticias/balacera-en-la-avenida-revolucion-tijuana-deja-3-heridos-hoy-1-noviembre',
        'https://www.tvaztecabajacalifornia.com/noticias/jefe-renunciaron-ministros-de-la-suprema-corte-justicia',
        'https://www.tvaztecabajacalifornia.com/noticias/balacera-tijuana-reciben-escuela-en-casa-del-terror-en-colonia-el-soler'
    )
),
('Azteca Yucatan',
    JSON_ARRAY(
        'https://www.aztecayucatan.com/clima/atencion-toda-de-baja-presion-aumenta-su-probabilidad-de-formar-el-ciclon-patty-frente-a-yucatan',
        'https://www.aztecayucatan.com/clima/manana-pronostica-fuertes-lluvias-para-el-clima-hoy-en-merida-viernes-01-de-noviembre-de-2024',
        'https://www.aztecayucatan.com/clima/frente-frio-6-y-nueva-onda-tropical-30-provocaran-fuertes-lluvias-en-estos-estados-del-pais'
    ),
    JSON_ARRAY(
        'https://www.aztecayucatan.com/noticias/video/ocho-las-ministras-y-ministros-ya-entregaron-su-renuncia',
        'https://www.aztecayucatan.com/noticias/video/en-el-ine-surgio-una-rebelion-la-votacion-judicial',
        'https://www.aztecayucatan.com/noticias/ministros-en-lo-particular-e-en-general-la-ley-supremacia-constitucional'
    )
),
-- Continue for each Azteca station...
('Azteca Veracruz',
    JSON_ARRAY(
        'https://www.aztecaveracruz.com/clima/veracruz-podria-tener-lluvias-por-posible-formacion-ciclon-tropical',
        'https://www.aztecaveracruz.com/deportes/dia-muertos-2024-recuerdan-a-diego-chavez-futbolista-veracruzano-fallecio-en-accidente-veh',
        'https://www.aztecaveracruz.com/noticias/precio-dolar-hoy-1-noviembre-2024-en-veracruz-en-cuanto-se-cotiza-este-dia-peso'
    ),
    JSON_ARRAY(
        'https://www.aztecaveracruz.com/noticias/cierre-la-autopista-ciudad-mendoza-puebla-que-ya-alterna-se-puede-tomar-el-desvio',
        'https://www.aztecaveracruz.com/noticias/que-ocurrio-hoy-31-octubre-en-el-centro-veracruz-que-hay-un-conductor-detenido',
        'https://www.aztecaveracruz.com/noticias/grupo-poder-en-la-suprema-corte-aprobo-la-ley-supremacia-constitucional'
    )
);
                          ''')
    ]
