# Generated by Django 5.1 on 2024-11-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20241104_0244'),
    ]

    operations = [
        migrations.RunSQL('''
update server_localrecord set name = "Azteca BC" where name = "Azteca BajaCalifornia";
update server_localrecord set name = "Azteca CJ" where name = "Azteca Ciudad Juarez";
                          ''')
    ]
