# Generated by Django 5.1 on 2025-01-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_initial_image_sites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagerecord',
            old_name='performance_score',
            new_name='note_value',
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='azteca',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='total_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagerecord',
            name='video_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
