# Generated by Django 5.1 on 2025-01-21 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_rename_amp_note_value_amprecord_note_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sitemap_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_first_contentful_paint', models.DecimalField(decimal_places=2, default=0, help_text='Time (in seconds) from page load to the first visible content. Lower values are better.', max_digits=5)),
                ('note_total_blocking_time', models.DecimalField(decimal_places=2, default=0, help_text='Total time (in seconds) the page was unresponsive to user input. High values indicate poor interactivity.', max_digits=5)),
                ('note_speed_index', models.DecimalField(decimal_places=2, default=0, help_text="Time (in seconds) for the page's content to become visually complete. Lower values are better.", max_digits=5)),
                ('note_largest_contentful_paint', models.DecimalField(decimal_places=2, default=0, help_text='Time (in seconds) to render the largest visible content element. Lower values indicate faster rendering.', max_digits=5)),
                ('note_cumulative_layout_shift', models.DecimalField(decimal_places=2, default=0, help_text='Score indicating unexpected layout shifts. Lower values are better.', max_digits=5)),
                ('video_first_contentful_paint', models.DecimalField(decimal_places=2, default=0, help_text='Time (in seconds) from video page load to the first visible content. Lower values are better.', max_digits=5)),
                ('video_total_blocking_time', models.DecimalField(decimal_places=2, default=0, help_text='Total time (in seconds) the video page was unresponsive to user input. High values indicate poor interactivity.', max_digits=5)),
                ('video_speed_index', models.DecimalField(decimal_places=2, default=0, help_text='Time (in seconds) for video page content to become visually complete. Lower values are better.', max_digits=5)),
                ('video_largest_contentful_paint', models.DecimalField(decimal_places=2, default=0, help_text='Time (in seconds) to render the largest visible content element on the video page. Lower values improve UX.', max_digits=5)),
                ('video_cumulative_layout_shift', models.DecimalField(decimal_places=2, default=0, help_text='Score indicating unexpected layout shifts on the video page. Lower values are better.', max_digits=5)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.imagesite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
