# Generated by Django 5.1 on 2025-01-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_lastjobrun_websitecheck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerecord',
            name='site',
        ),
    ]
