# Generated by Django 5.1 on 2024-11-20 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0011_dataupload"),
    ]

    operations = [
        migrations.AddField(
            model_name="localrecord",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="server.localsite",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="server.site",
            ),
        ),
    ]
