# Generated by Django 5.1 on 2024-11-22 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0012_localrecord_site_record_site"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localrecord",
            name="amp_note_value",
        ),
        migrations.RemoveField(
            model_name="localrecord",
            name="amp_total_value",
        ),
        migrations.RemoveField(
            model_name="localrecord",
            name="amp_video_value",
        ),
        migrations.RemoveField(
            model_name="record",
            name="amp_note_value",
        ),
        migrations.RemoveField(
            model_name="record",
            name="amp_total_value",
        ),
        migrations.RemoveField(
            model_name="record",
            name="amp_video_value",
        ),
        migrations.CreateModel(
            name="AmpRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("amp_note_value", models.FloatField(blank=True, null=True)),
                ("amp_video_value", models.FloatField(blank=True, null=True)),
                ("amp_total_value", models.FloatField(blank=True, null=True)),
                ("azteca", models.BooleanField(default=False)),
                ("date", models.DateField(null=True)),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.localsite",
                    ),
                ),
            ],
        ),
    ]
