# Generated by Django 5.1 on 2024-11-22 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0013_remove_localrecord_amp_note_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amprecord",
            name="site",
        ),
    ]
