# Generated by Django 5.1 on 2024-11-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0014_remove_amprecord_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="amprecord",
            name="note_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Cumulative Layout Shift (CLS) score, which measures unexpected layout shifts during page load. A higher score indicates that the page layout shifted unexpectedly, leading to a poor user experience. A lower score is better.",
            ),
        ),
        migrations.AddField(
            model_name="amprecord",
            name="note_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the page starts loading until the first piece of content (e.g., text, image) is rendered on the screen. Lower values indicate faster rendering.",
            ),
        ),
        migrations.AddField(
            model_name="amprecord",
            name="note_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the page starts loading until the largest visible content element (e.g., image, video, text block) is fully rendered. Lower values indicate quicker rendering of important content.",
            ),
        ),
        migrations.AddField(
            model_name="amprecord",
            name="note_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Speed Index score (measured in seconds) that reflects how quickly the page's content becomes visually complete. Lower values are better, as they indicate faster visual rendering of the page.",
            ),
        ),
        migrations.AddField(
            model_name="amprecord",
            name="note_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) during which the page was blocked and unable to respond to user input, such as clicks or typing. High values indicate poor interactivity and can negatively affect the user experience.",
            ),
        ),
        migrations.AddField(
            model_name="amprecord",
            name="video_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Cumulative Layout Shift (CLS) score for the video page, which measures unexpected layout shifts during page load. A higher value indicates that the layout shifted unexpectedly, causing a poor user experience. Lower values are preferred.",
            ),
        ),
        migrations.AddField(
            model_name="amprecord",
            name="video_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the video page starts loading until the first visible content (e.g., text, image) is rendered on the screen. Lower values indicate faster visual rendering of the video page.",
            ),
        ),
        migrations.AddField(
            model_name="amprecord",
            name="video_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the video page starts loading until the largest content element (e.g., image, video, text block) is fully rendered. Faster rendering of important content improves the user experience.",
            ),
        ),
        migrations.AddField(
            model_name="amprecord",
            name="video_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Speed Index score (measured in seconds) indicating how quickly the video page content becomes visually complete. Lower values are better, indicating faster loading and rendering of the page.",
            ),
        ),
        migrations.AddField(
            model_name="amprecord",
            name="video_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) during which the video page was blocked and unable to respond to user input. High values indicate a delay in interactivity and can negatively affect the user experience.",
            ),
        ),
        migrations.AddField(
            model_name="localrecord",
            name="note_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Cumulative Layout Shift (CLS) score, which measures unexpected layout shifts during page load. A higher score indicates that the page layout shifted unexpectedly, leading to a poor user experience. A lower score is better.",
            ),
        ),
        migrations.AddField(
            model_name="localrecord",
            name="note_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the page starts loading until the first piece of content (e.g., text, image) is rendered on the screen. Lower values indicate faster rendering.",
            ),
        ),
        migrations.AddField(
            model_name="localrecord",
            name="note_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the page starts loading until the largest visible content element (e.g., image, video, text block) is fully rendered. Lower values indicate quicker rendering of important content.",
            ),
        ),
        migrations.AddField(
            model_name="localrecord",
            name="note_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Speed Index score (measured in seconds) that reflects how quickly the page's content becomes visually complete. Lower values are better, as they indicate faster visual rendering of the page.",
            ),
        ),
        migrations.AddField(
            model_name="localrecord",
            name="note_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) during which the page was blocked and unable to respond to user input, such as clicks or typing. High values indicate poor interactivity and can negatively affect the user experience.",
            ),
        ),
        migrations.AddField(
            model_name="localrecord",
            name="video_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Cumulative Layout Shift (CLS) score for the video page, which measures unexpected layout shifts during page load. A higher value indicates that the layout shifted unexpectedly, causing a poor user experience. Lower values are preferred.",
            ),
        ),
        migrations.AddField(
            model_name="localrecord",
            name="video_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the video page starts loading until the first visible content (e.g., text, image) is rendered on the screen. Lower values indicate faster visual rendering of the video page.",
            ),
        ),
        migrations.AddField(
            model_name="localrecord",
            name="video_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the video page starts loading until the largest content element (e.g., image, video, text block) is fully rendered. Faster rendering of important content improves the user experience.",
            ),
        ),
        migrations.AddField(
            model_name="localrecord",
            name="video_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Speed Index score (measured in seconds) indicating how quickly the video page content becomes visually complete. Lower values are better, indicating faster loading and rendering of the page.",
            ),
        ),
        migrations.AddField(
            model_name="localrecord",
            name="video_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) during which the video page was blocked and unable to respond to user input. High values indicate a delay in interactivity and can negatively affect the user experience.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="note_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Cumulative Layout Shift (CLS) score, which measures unexpected layout shifts during page load. A higher score indicates that the page layout shifted unexpectedly, leading to a poor user experience. A lower score is better.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="note_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the page starts loading until the first piece of content (e.g., text, image) is rendered on the screen. Lower values indicate faster rendering.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="note_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the page starts loading until the largest visible content element (e.g., image, video, text block) is fully rendered. Lower values indicate quicker rendering of important content.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="note_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Speed Index score (measured in seconds) that reflects how quickly the page's content becomes visually complete. Lower values are better, as they indicate faster visual rendering of the page.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="note_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) during which the page was blocked and unable to respond to user input, such as clicks or typing. High values indicate poor interactivity and can negatively affect the user experience.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="video_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Cumulative Layout Shift (CLS) score for the video page, which measures unexpected layout shifts during page load. A higher value indicates that the layout shifted unexpectedly, causing a poor user experience. Lower values are preferred.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="video_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the video page starts loading until the first visible content (e.g., text, image) is rendered on the screen. Lower values indicate faster visual rendering of the video page.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="video_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from when the video page starts loading until the largest content element (e.g., image, video, text block) is fully rendered. Faster rendering of important content improves the user experience.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="video_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Speed Index score (measured in seconds) indicating how quickly the video page content becomes visually complete. Lower values are better, indicating faster loading and rendering of the page.",
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="video_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) during which the video page was blocked and unable to respond to user input. High values indicate a delay in interactivity and can negatively affect the user experience.",
            ),
        ),
    ]
