# Generated by Django 5.1 on 2024-11-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0015_amprecord_note_cumulative_layout_shift_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amprecord",
            name="note_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Score indicating unexpected layout shifts. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="amprecord",
            name="note_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from page load to the first visible content. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="amprecord",
            name="note_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) to render the largest visible content element. Lower values indicate faster rendering.",
            ),
        ),
        migrations.AlterField(
            model_name="amprecord",
            name="note_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) for the page's content to become visually complete. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="amprecord",
            name="note_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) the page was unresponsive to user input. High values indicate poor interactivity.",
            ),
        ),
        migrations.AlterField(
            model_name="amprecord",
            name="video_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Score indicating unexpected layout shifts on the video page. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="amprecord",
            name="video_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from video page load to the first visible content. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="amprecord",
            name="video_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) to render the largest visible content element on the video page. Lower values improve UX.",
            ),
        ),
        migrations.AlterField(
            model_name="amprecord",
            name="video_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) for video page content to become visually complete. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="amprecord",
            name="video_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) the video page was unresponsive to user input. High values indicate poor interactivity.",
            ),
        ),
        migrations.AlterField(
            model_name="localrecord",
            name="note_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Score indicating unexpected layout shifts. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="localrecord",
            name="note_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from page load to the first visible content. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="localrecord",
            name="note_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) to render the largest visible content element. Lower values indicate faster rendering.",
            ),
        ),
        migrations.AlterField(
            model_name="localrecord",
            name="note_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) for the page's content to become visually complete. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="localrecord",
            name="note_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) the page was unresponsive to user input. High values indicate poor interactivity.",
            ),
        ),
        migrations.AlterField(
            model_name="localrecord",
            name="video_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Score indicating unexpected layout shifts on the video page. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="localrecord",
            name="video_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from video page load to the first visible content. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="localrecord",
            name="video_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) to render the largest visible content element on the video page. Lower values improve UX.",
            ),
        ),
        migrations.AlterField(
            model_name="localrecord",
            name="video_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) for video page content to become visually complete. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="localrecord",
            name="video_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) the video page was unresponsive to user input. High values indicate poor interactivity.",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="note_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Score indicating unexpected layout shifts. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="note_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from page load to the first visible content. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="note_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) to render the largest visible content element. Lower values indicate faster rendering.",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="note_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) for the page's content to become visually complete. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="note_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) the page was unresponsive to user input. High values indicate poor interactivity.",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="video_cumulative_layout_shift",
            field=models.IntegerField(
                default=0,
                help_text="Score indicating unexpected layout shifts on the video page. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="video_first_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) from video page load to the first visible content. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="video_largest_contentful_paint",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) to render the largest visible content element on the video page. Lower values improve UX.",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="video_speed_index",
            field=models.IntegerField(
                default=0,
                help_text="Time (in seconds) for video page content to become visually complete. Lower values are better.",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="video_total_blocking_time",
            field=models.IntegerField(
                default=0,
                help_text="Total time (in seconds) the video page was unresponsive to user input. High values indicate poor interactivity.",
            ),
        ),
    ]
